### GET retreive all suppliers
GET http://localhost:8080/api/v1/auth/suppliers

### GET retreive supplier by id
GET http://localhost:8080/api/v1/auth/supplier/1

### POST add supplier
POST http://localhost:8080/api/v1/auth/supplier/add
Content-Type: application/json

{
  "registrationNumber": "6543211",
  "supplierAddressDto": {
    "id": 1
  },
  "supplierProductDto": {
    "id": 1
  }
}

### PUT update a supplier
PUT http://localhost:8080/api/v1/auth/supplier/update
Content-Type: application/json

{
  "id": 5,
  "registrationNumber": "6543211 update",
  "supplierAddressDto": {
    "id": 1
  },
  "supplierProductDto": {
    "id": 2
  }
}

### DELETE a supplier
DELETE http://localhost:8080/api/v1/auth/supplier/5/delete

### PUT add address to supplier
PUT http://localhost:8080/api/v1/auth/supplier/1/address
Content-Type: application/json

{
  "street": "Rue malherbe created",
  "city": "Ville de france created",
  "number": "B15 created",
  "country": "HelioPolis created"
}

### PUT add product to supplier
PUT http://localhost:8080/api/v1/auth/supplier/1/product
Content-Type: application/json

{
  "name": "Apple TV created",
  "quantity": 3,
  "price": 12,
  "url": "photoAppleTV2.png"
}