### POST upload a file in server
POST {{host}}:{{port}}/api/v1/auth/file/upload
Content-Type: multipart/form-data; boundary=----boundary

------boundary
Content-Disposition: form-data; name="file"; filename="test.txt"
Content-Type: text/plain

< C:/Users/thoma/Downloads/test.txt
------boundary--

### GET a file by name
GET {{host}}:{{port}}/api/v1/auth/file/tt.png

### GET retrieve all files names
GET {{host}}:{{port}}/api/v1/auth/files
Content-Type: text/plain

### GET retrieve all files with content
GET {{host}}:{{port}}/api/v1/auth/files/content