### GET All Addresses
GET {{host}}:{{port}}/api/v1/auth/address

### GET All Countries
GET {{host}}:{{port}}/api/v1/auth/address/countries

### GET address by ID
GET {{host}}:{{port}}/api/v1/auth/address/1

### POST add address
POST {{host}}:{{port}}/api/v1/auth/address/add
Content-Type: application/json

{
  "street": "Rue malherbe created",
  "city": "Ville de france created",
  "number": "B15",
  "country": "BE"
}

### PUT update address
PUT {{host}}:{{port}}/api/v1/auth/address/update
Content-Type: application/json

{
  "id": 6,
  "street": "Rue malherbe Updated",
  "city": "Ville de france Updated",
  "number": "B15 Updated",
  "country": "FR"
}

### DELETE address by id
DELETE {{host}}:{{port}}/api/v1/auth/address/1/delete