### POST payment checkout
POST {{host}}:{{port}}/api/v1/auth/checkout
Content-Type: application/json

{
  "amount": 1100,
  "quantity": 1,
  "currency": "USD",
  "name": "specialUUID",
  "email": "thomas@hotmail.com",
  "productBasket": [
    {
      "productId": 1,
      "quantity": 2
    },
    {
      "productId": 2,
      "quantity": 3
    }
  ]
}