### REGISTER USER

POST http://localhost:8080/api/v1/auth/register
Content-Type: application/json

{"username": "koba", "email": "koba@hotmail.com", "password": "1234"}


### LOGIN USER
POST http://localhost:8080/api/v1/auth/login
Content-Type: application/json

{"email": "thomas@hotmail.com","password": "1234"}


### GET USER INFORMATION
GET http://localhost:8080/api/v1/user
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ0aG9tYXNAaG90bWFpbC5jb20iLCJpYXQiOjE3NTMxODA3NTEsImV4cCI6MTc1MzE4MTY1MX0.dkv_bx7l6dlJ1TtWklnNd-C_MePrxPCOTcHDx-pfOCE


### POST RESET PASSWORD
POST  http://localhost:8080/api/v1/auth/password-reset
Content-Type: application/json

{
  "email": "thomas@hotmail.com",
  "newPassword": "5678"
}