### REGISTER USER

POST http://localhost:8080/api/v1/auth/register
Content-Type: application/json

{"username": "koba", "email": "koba@hotmail.com", "password": "1234"}


### LOGIN USER
POST http://localhost:8080/api/v1/auth/login
Content-Type: application/json

{"email": "thomas@hotmail.com","password": "1234"}


### GET USER INFORMATION
GET http://localhost:8080/api/v1/user
Authorization: Bearer 123

### POST RESET PASSWORD
POST  http://localhost:8080/api/v1/auth/password-reset
Content-Type: application/json

{
  "email": "thomas@hotmail.com",
  "newPassword": "5678"
}