### REGISTER USER

POST http://localhost:8080/api/v1/auth/register
Content-Type: application/json

{"username": "koba", "email": "koba@hotmail.com", "password": "1234"}


### LOGIN USER

POST http://localhost:8080/api/v1/auth/login
Content-Type: application/json

{"email": "koba@hotmail.com","password": "1234"}


### GET USER INFORMATION
GET http://localhost:8080/api/v1/user
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ0aG9tYXNAaG90bWFpbC5jb20iLCJpYXQiOjE3NDEwOTk4NzgsImV4cCI6MTc0MTEwMDc3OH0.i6rN4WgkfqKKDs3IUm5nWAWaRSW1cnC3O6cLTZeRoTc