### GET all orders
GET http://localhost:8080/api/v1/auth/orders

### GET order by id
GET http://localhost:8080/api/v1/auth/order/2

### POST add an order
POST http://localhost:8080/api/v1/auth/order/add
Content-Type: application/json

{
  "createAt": "2025-03-06T17:00:00Z",
  "isDone": false,
  "client": {
    "email": "thomas@hotmail.com"
  }
}

### GET retrieve order product by email and orderId
GET http://localhost:8080/api/v1/auth/order-products?email=thomas@hotmail.com&orderId=1

### TOGGLE COMPLETED ORDER
PUT http://localhost:8080/api/v1/auth/order/complete/1

### GET retrieve orders product by email
GET http://localhost:8080/api/v1/auth/order-products/thomas@hotmail.com

### GET retrieve orders product with detailed
GET http://localhost:8080/api/v1/auth/order-products/detailed


### GET creating billing by email
GET http://localhost:8080/api/v1/auth/order-products/billing?email=thomas@hotmail.com&orderId=1