### POST REQUEST AMQ

POST {{host}}:{{port}}/api/v1/auth/amq/products
Content-Type: application/json

{ "id":1,"name": "error","quantity": 2,"price": 3.5}

### SEND MESSAGE FROM USER

POST {{host}}:{{port}}/api/v1/auth/amq/contact
Content-Type: application/json

{
  "nom": "james",
  "email": "userTest@exemple.com",
  "sujet": "test message",
  "message": "Ceci est un test de user"
}