### GET All comments
GET http://localhost:8080/api/v1/auth/comments

### GET comment by id
GET http://localhost:8080/api/v1/auth/comment/1

### PUT update a comment
PUT http://localhost:8080/api/v1/auth/comment/update
Content-Type: application/json

{
  "id": 1,
  "header": "Header update",
  "body": "Body update",
  "createAt": "2025-02-27T11:18:39Z",
  "updateAt": "2025-02-27T11:18:39Z"
}

### POST add comment
POST http://localhost:8080/api/v1/auth/comment/add
Content-Type: application/json

{
  "header": "Header created",
  "body": "Body created",
  "createAt": "2025-02-27T11:18:39Z",
  "updateAt": "2025-02-27T11:18:39Z"
}

### DELETE comment
DELETE http://localhost:8080/api/v1/auth/comment/2/delete
