### GET all images
GET {{host}}:{{port}}/api/v1/auth/images

### GET image by id
GET {{host}}:{{port}}/api/v1/auth/image/1

### DELETE image
DELETE {{host}}:{{port}}/api/v1/auth/image/1/delete

### POST add image to product id
POST {{host}}:{{port}}/api/v1/auth/image/add/1
Content-Type: application/json

{
  "path": "testPost"
}

### DELETE BY IMAGE NAME AND PRODUCT ID => image/delete/{imageName}/{productId}
DELETE {{host}}:{{port}}/api/v1/auth/image/delete/test2.png/1

### PUT update a image
PUT {{host}}:{{port}}/api/v1/auth/image/update
Content-Type: application/json

{
  "id": 9,
  "path": "testPost-update"
}