### GET All category
GET {{host}}:{{port}}/api/v1/auth/category

### GET category by id
GET {{host}}:{{port}}/api/v1/auth/category/2

### POST category
POST {{host}}:{{port}}/api/v1/auth/category/add
Content-Type: application/json

{
    "name": "Other"
}

### PUT Update category
PUT {{host}}:{{port}}/api/v1/auth/category/update
Content-Type: application/json

{
  "id": 1,
  "name": "Laptop Updated"
}

### DELETE category
DELETE {{host}}:{{port}}/api/v1/auth/category/1/delete