### GET ALL PRODUCTS
GET http://localhost:8080/api/v1/auth/products

### GET PRODUCTS WITH PAGE
GET http://localhost:8080/api/v1/auth/products/page?pageNo=1&pageSize=2

### GET PRODUCT BY ID
GET http://localhost:8080/api/v1/auth/product/1

### ADD PRODUCT
POST http://localhost:8080/api/v1/auth/product/1/add
Content-Type: application/json

{
  "name": "Apple TV",
  "quantity": 5,
  "price": 120,
  "url": "photoAppleTV2.png"
}

### DELETE PRODUCT BY ID
DELETE http://localhost:8080/api/v1/auth/product/5/delete

### UPDATED PRODUCT
PUT http://localhost:8080/api/v1/auth/product/update
Content-Type: application/json

{
  "id":1,
  "name": "Dell i9 updated",
  "price": 25.5,
  "url": "photo Dell i9",
  "quantity": 3,
  "categoryInnerProductDto": {
    "id": 1,
    "name": "Laptop"
  }
}