### GET ENV VAR
GET {{host}}:{{port}}/api/v1/auth/env

### GET ALL PRODUCTS
GET {{host}}:{{port}}/api/v1/auth/products

### GET PRODUCT BY CATEGORY_ID
GET {{host}}:{{port}}/api/v1/auth/products/category/1

### GET PRODUCTS WITH PAGE
GET {{host}}:{{port}}/api/v1/auth/products?pageNo=1&pageSize=2

### GET PRODUCT BY ID
GET {{host}}:{{port}}/api/v1/auth/product/1

### ADD PRODUCT WITH CATEGORY IN PARAM
POST {{host}}:{{port}}/api/v1/auth/product/1/add
Content-Type: application/json

{
  "name": "Apple TV",
  "quantity": 5,
  "price": 120,
  "url": "test1.png"
}

### DELETE PRODUCT BY ID
DELETE {{host}}:{{port}}/api/v1/auth/product/5/delete


### UPDATED PRODUCT
PUT {{host}}:{{port}}/api/v1/auth/product/update
Content-Type: application/json

{
  "id":1,
  "name": "Dell i9 updated",
  "price": 25.5,
  "url": "photo Dell i9",
  "quantity": 3,
  "categoryInnerProductDto": {
    "id": 1,
    "name": "Laptop"
  }
}