### GET All client
GET http://localhost:8080/api/v1/auth/clients

### GET client by id
GET http://localhost:8080/api/v1/auth/client/1

### LOGIN USER
POST http://localhost:8080/api/v1/auth/login
Content-Type: application/json

{"email": "thomas@hotmail.com","password": "1234"}

### PUT update a client
PUT http://localhost:8080/api/v1/auth/client/update
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ0aG9tYXNAaG90bWFpbC5jb20iLCJpYXQiOjE3NDExNjM1NDgsImV4cCI6MTc0MTE2NDQ0OH0.A013jL6ZD6Itz-VhtvtoXKu9sNmeztnXuDNiMvuxbAs

{
  "street": "Rue malherbe Updated",
  "city": "Ville de france Updated",
  "number": "B15 Updated",
  "country": "HelioPolis Updated"
}

### POST add address to a client
POST http://localhost:8080/api/v1/client/auth/address
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ0aG9tYXNAaG90bWFpbC5jb20iLCJpYXQiOjE3NDExNjUxOTMsImV4cCI6MTc0MTE2NjA5M30.Kr_j06bK0IAkBCUNMZyyfNg6K9ZnJxF-UhU3I7Us2VI

{
  "street": "Rue malherbe created",
  "city": "Ville de france created",
  "number": "B15 created",
  "country": "HelioPolis created"
}

### POST add comment to a client
POST http://localhost:8080/api/v1/auth/client/comment
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ0aG9tYXNAaG90bWFpbC5jb20iLCJpYXQiOjE3NDExNjc4ODMsImV4cCI6MTc0MTE2ODc4M30.2MFruAx2QTn8SPdmKlFJcFhpxY9jTtYF2t8FjPDLhlg

{
  "header": "Header created 1",
  "body": "Body created 1",
  "createAt": "2025-03-05T12:19:39Z",
  "updateAt": "2025-03-05T12:19:39Z"
}

### DELETE delete by id
DELETE http://localhost:8080/api/v1/auth/client/1/delete